name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker.io/${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.3.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker stop my-app || true
            docker rm my-app || true
            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
            docker run -d --name my-app -p 80:80 docker.io/${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
