name: My Workflow

on:
  push:
  
    branches:
      - master
      - "future/**"
      
    branches-ignore:
      - "feature/feature_ignore"
      
    paths:
      - "**.js"
      - "!sample.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: echo "This is a bash script on Ubuntu"
