name: simple environment variables

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: "Hello World"

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      - name: Print environment variable
        run: echo $MY_VARIABLE
