name: simple secret

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use a secret in a script
        run: |
          echo "The secret value is ${{ secrets.MY_SECRET }}"
