name: My  Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: custome actions
      uses: ./.github/actions/hello
      id: hello
      with:
        who-to-greet: "world"
    - run: |
        echo "Time:${{steps.hello.outputs.time}}"
