name: My Simple Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install @actions/github

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: hello world actions
      uses: ./.github/actions/hello
      id: hello
      with:
        who-to-greet: "world"
    - run: |
        echo "Time:${{steps.hello.outputs.time}}"

    - name: issues
      uses: ./.github/actions/issues
      id: issues
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        title: build issue
        body: Body
        assignees: |
          koteshwarraomyneni
    - run: echo ${{steps.issues.output.issues}}


